# Generated by Django 3.2 on 2022-12-12 04:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='ФИО')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
                ('address', models.CharField(max_length=50, verbose_name='Адрес')),
                ('phone_number', models.CharField(max_length=13, verbose_name='Номер телефона')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='ФИО')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
                ('position', models.CharField(max_length=40, verbose_name='Должность')),
                ('salary', models.IntegerField(verbose_name='Зарплата')),
                ('work_experience', models.DateField(verbose_name='Дата принятия')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worker.employee')),
            ],
        ),
        migrations.CreateModel(
            name='VIPClient',
            fields=[
                ('client_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='worker.client')),
                ('vip_status_start', models.DateField(verbose_name='Дата начала вип-статуса')),
                ('donation_amount', models.IntegerField(verbose_name='Сумма пожертвования')),
            ],
            options={
                'abstract': False,
            },
            bases=('worker.client',),
        ),
        migrations.CreateModel(
            name='WorkProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=50, verbose_name='Название проекта')),
                ('employee', models.ManyToManyField(related_name='workprojects', through='worker.Membership', to='worker.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='Passport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inn', models.CharField(max_length=14, verbose_name='ИНН паспорта')),
                ('id_card', models.CharField(max_length=8, verbose_name='Номер ID паспорта')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passports', to='worker.employee')),
            ],
        ),
        migrations.AddField(
            model_name='membership',
            name='work_project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worker.workproject'),
        ),
    ]
